### ISSUE TITLE
[QUERY] Can this package be used with cloudflare workers?

### ISSUE THREAD

**Issue by johtso** [slackapi/deno-slack-api#116]
I'm currently trying to get started interacting with the Slack web api in the Cloudflare workers runtime.

Unfortunately the main client uses axios, and I don't seem to be able to get it running on cloudflare (I get a `Uncaught Error: Dynamic require of "node:path" is not supported` error)

Seeing as the deno runtime is very similar to the cloudflare runtime, I was wondering if it's possible to somehow install and use it there?

**Comment by vegeris** [comment]
Hi there, 

[Deno's documentation](https://docs.deno.com/runtime/tutorials/cloudflare_workers/) suggests Deno apps should be able to run on Cloudflare Workers, so there might be a way to run this module there!

If there's a problem using this library, you could also try [this](https://github.com/seratch/slack-web-api-client) project from a member of our team, which natively supports Cloudflare Workers

Otherwise we have a list of commonly used cloud providers [here](https://api.slack.com/distribution/hosting)

**Comment by johtso** [comment]
@vegeris ah amazing, that looks like exactly what I've been looking for, shame I didn't stumble across it while googling earlier. Cheers!
