### ISSUE TITLE
[FEATURE] apiCall support other HTTP methods

### ISSUE THREAD

**Issue by whywaita** [slackapi/deno-slack-api#85]
### Description

Now, `apiCall()` only supports POST method.

https://github.com/slackapi/deno-slack-api/blob/368e4064f836b222178cfc7722d377d46baea118/src/base-client.ts#L42

But Slack API has other HTTP methods.
So `apiCall` needs to support other HTTP methods.

### Suggestion

1.  Add `apiCallWithHTTPMethods()`

```
  async apiCallWithHTTPMethods(
    http_methods: string,
    method: string,
    data: SlackAPIMethodArgs = {},
  ): Promise<BaseResponse> {
  }
```

2. Add `apiPostCall()`,  `apiGetCall()`, `apiDeleteCall()` and more

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](../CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by seratch** [comment]
Hi @whywaita, thanks for taking the time to send this suggestion! 

Indeed, our Web API documents mention a recommended HTTP method to use for an API call. However, in reality, all the Slack API endpoints can be accessed with the HTTP POST method, and that's why this SDK consistently uses it for all the APIs (also, this is the same for other existing SDKs such as Node.js, Python, and Java ones). Not following the recommended HTTP methods in documents can reduce this team's maintenance efforts, thus we don't have plans to change this in the short term.

Thanks again for your time and interest, and we apologize for the confusion with the API documents! Let me close this issue now.

**Comment by whywaita** [comment]
hum I see, I will wait for all APIs to become using POST.
